apiVersion: platform.confluent.io/v1beta1
kind: KafkaTopic
metadata:
  name: expedia
  namespace: confluent
spec:
  replicas: 3
  partitionCount: 3
  configs:
    cleanup.policy: "delete"
---
apiVersion: platform.confluent.io/v1beta1
kind: KafkaTopic
metadata:
  name: expedia-ext
  namespace: confluent
spec:
  replicas: 3
  partitionCount: 3
  configs:
    cleanup.policy: "delete"